Feature/paylsquad3 1085
PaylinePaymentMethod/payment-method-wechatpay pull request #3
Opened 2021-05-03 13:12 UTC by Monext-kkaddour

2021-05-03 13:30 UTC, pesublet commented on src/main/resources/messages_fr.properties
> +contract.partnerTransactionId.edel = Edel
Pour être cohérent avec Alipay, j'aurais mis "Formalisme Edel", mais peut être que Jérome a demandé "Edel" pour celui ci ?

2021-05-03 14:06 UTC, pesublet requested changes
Super ! 2-3 petites modifs et on est bon 👍

2021-05-03 14:06 UTC, pesublet commented on src/test/java/com/payline/payment/wechatpay/service/PartnerTransactionIdServiceTest.java
> +    }
Tu devrais pourvoir simplifier un peu ici l'initialisation :
```suggestion
    @Spy
    private PartnerTransactionIdService underTest = PartnerTransactionIdService.getInstance();
```

2021-05-04 09:16 UTC, Monext-kkaddour commented on src/main/resources/messages_fr.properties
> +contract.partnerTransactionId.edel = Edel
done

2021-05-04 09:16 UTC, Monext-kkaddour commented on src/main/java/com/payline/payment/wechatpay/service/impl/PaymentServiceImpl.java
> +        PartnerTransactionIdService partnerTransactionIdService = PartnerTransactionIdService.getInstance();
done

2021-05-04 09:17 UTC, Monext-kkaddour commented on src/test/java/com/payline/payment/wechatpay/service/PartnerTransactionIdServiceTest.java
> +    }
done

2021-05-04 09:47 UTC, pesublet approved these changes

2021-05-04 09:50 UTC, merged